# Generated by Django 3.2.6 on 2021-08-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=2000)),
                ('city', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('date', models.DateField()),
                ('team1', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('team2', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('toss_winner', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('toss_decision', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('result', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('dl_applied', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('win_by_runs', models.IntegerField(default=0)),
                ('win_by_wickets', models.IntegerField(default=0)),
                ('player_of_match', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('venue', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('umpire1', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('umpire2', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('umpire3', models.CharField(blank=True, default=None, max_length=225, null=True)),
            ],
        ),
    ]
