# Generated by Django 3.2.6 on 2021-08-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(default=1)),
                ('inning', models.IntegerField(default=1, max_length=1)),
                ('batting_team', models.CharField(default=None, max_length=22)),
                ('bowling_team', models.CharField(default=None, max_length=22)),
                ('over', models.IntegerField(default=1)),
                ('ball', models.IntegerField(default=1)),
                ('batsman', models.CharField(default=None, max_length=22)),
                ('non_striker', models.CharField(default=None, max_length=22)),
                ('bowler', models.CharField(default=None, max_length=22)),
                ('is_super_over', models.BooleanField(default=False)),
                ('wide_runs', models.IntegerField(default=0)),
                ('bye_runs', models.IntegerField(default=1)),
                ('legbye_runs', models.IntegerField(default=1)),
                ('noball_runs', models.IntegerField(default=1)),
                ('penalty_runs', models.IntegerField(default=1)),
                ('batsman_runs', models.IntegerField(default=1)),
                ('extra_runs', models.IntegerField(default=1)),
                ('total_runs', models.IntegerField(default=1)),
                ('player_dismissed', models.CharField(default=None, max_length=22)),
                ('dismissal_kind', models.CharField(default=None, max_length=22)),
                ('fielder', models.CharField(default=None, max_length=22)),
            ],
        ),
    ]
