# Generated by Django 3.2.6 on 2021-08-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gale', '0002_deliveries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='inning',
            field=models.IntegerField(default=1),
        ),
    ]
