# Generated by Django 3.2.6 on 2021-08-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gale', '0003_alter_deliveries_inning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='dismissal_kind',
            field=models.CharField(blank=True, default=None, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='fielder',
            field=models.CharField(blank=True, default=None, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='player_dismissed',
            field=models.CharField(blank=True, default=None, max_length=22, null=True),
        ),
    ]
